openapi: '3.0.2'
info:
  title: Woordify Server
  version: '1.3.0'
servers:
  - url: http://localhost:3333
paths:
  /woorden:
    get:
      description: get or create current word list
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /info:
    get:
      responses:
        '200': 
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: "Woordify v1.2.0"
  /{date}:
    get:
      parameters:
        - in: path
          name: date
          required: true
          schema:
            type: string 
      description: get Words of given date
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
